### ISSUE TITLE
docker-compose搭建nginx和node

### ISSUE THREAD

**Issue by wuxiangang** [wuxiangang/questions#42]
### Nginx配置
 > docker-compose
```
version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    # 对应nginx服务启动端口
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # nginx配置文件相对路径
      - ./conf.d:/etc/nginx/conf.d
      # 静态资源相对路径
      - ./data:/var/www
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
```

> nginx.conf
```
http {
     ......
     # 对应的路径应为docker内的路径
     include /etc/nginx/conf.d/*.conf;
}
```

> conf.d/test.conf
```
server {
        gzip on;
        listen       8000 default_server;
        listen       [::]:8000 default_server;
        server_name  _;

        # 对应的路径应为docker内的路径
        root         /var/www/web;

        include /etc/nginx/default.d/*.conf;

        error_page 404 /404.html;
                location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
                location = /50x.html {
        }
}
```

###  node服务配置
 > docker-compose
```
version: '3'
services:
  server:
    image: node-server
    container_name: server
    # restart: unless-stopped
    environment:
      - LANG=C.UTF-8
    # 不需要重新安装依赖包就不需要build
    build: .
    volumes:
      - .:/src
      # 必须要，不然找不到依赖
      - /src/node_modules
    ports:
      - 7678:7678
    # command可以写在Dockerfile
    # command: node index.js
```

>Dockerfile
```
FROM node:12

RUN mkdir /src

EXPOSE 7678

WORKDIR /src

# 不需要重新安装依赖包就不需要build,直接将对应依赖上传到服务
ADD package.json /src/package.json
ADD yarn.lock /src/yarn.lock
RUN yarn global add pm2
RUN yarn install

ADD  . /src
# command可以写在docker-compose.yml
CMD pm2-docker index.js
```

> 常用命令
```
# 进入镜像
docker run -it [image-name] bash
docker run -it node-server bash

# 容器执行命令行
docker exec -it [container-name, id] pm2 list
docker exec -it server pm2 list

# 查看镜像
docker images

# 镜像清理
docker image prune

# 查看容器
docker container ls

docker-compose ps

# 启动docker-compose
docker-compose up -d

# 关闭
docker-compose down

# 重新打包
docker-compose build

# 删除镜像 -f 强制
docker rmi [-f] [image name, image id]

#删除所有镜像
docker rmi -f $(docker images -qa)

# 删除所有容器
docker rm $(docker ps -a -q)

# 参照上面node-server镜像，每次重启的步骤
docker-compose down
# 不需要build以下两步不需要
# ---------------------
docker rmi node-server:latest
docker-compose build
# ---------------------
docker-compose up -d
```
